server:
  port: 8086

spring:
  application:
    name: db-start
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5439}/${DB_NAME:fizmath}
    username: ${DB_USER:fizmath}
    password: ${DB_PASSWORD:fizmath}
  liquibase:
    change-log: db/changeLog.xml
