stages:
  - build

cache:
  paths:
    - .m2/repository

before_script:
  - rm -rf /opt/docker/db-start/*.jar

build:
  stage: build
  script:
    - mvn clean package -Dmaven.test.failrue.ignore=true
    - cp ./target/*.jar /opt/docker/db-start
    - docker-compose -f /opt/docker/docker-compose.yml up --build -d db-start
  only:
    - test
  tags:
    - teacher181
