create table "_user"
(
    id bigint primary key generated by default as identity,
    username varchar
    constraint ukr43af9ap4edm43mmtq01oddj6 unique,
    email    varchar
    constraint uk6dotkott2kjsp8vw4d0m25fb7 unique,
    password varchar
);

create table role
(
    id integer primary key generated by default as identity,
    name varchar
);

create table user_role
(
    user_id bigint not null
        constraint fkhfh9dx7w3ubf1co1vdev94g3f
            references "_user",
    role_id integer not null
        constraint fkh8ciramu9cc9q3qcqiv4ue8a6
            references role,
    primary key (user_id, role_id)
);


